title: Custom Objects Editor
description: Create and manage custom objects on the commercetools platform.
remote_theme: pmarsceill/just-the-docs
aux_links:
  'View on GitHub':
    - '//github.com/ariessolutionsio/custom-objects-editor/'
footer_content: ''
logo: 'assets/Labs-For-Dk_BG.svg'
color_scheme: aries
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
